#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/15/2021 18:55:16
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace DANMIS_NEW.Models
{
    public partial class BrandRepository : Repository<Brand>, IBrandRepository
    {
        public BrandRepository(DbContext _context) : base(_context)
        {
        }
    }
}
#pragma warning restore 1591
