//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANMIS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUF0015
    {
        public string CORP_NO { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_ABBR { get; set; }
        public string CUST_NAME_ENG { get; set; }
        public string CUST_AGENCY { get; set; }
        public string CUST_ADDR { get; set; }
        public string INVO_TITLE { get; set; }
        public string INVO_ADDR { get; set; }
        public string INVO_NO { get; set; }
        public string CHIEF_NAME { get; set; }
        public Nullable<decimal> CAPITAL_AMT { get; set; }
        public Nullable<decimal> CRED_AMT { get; set; }
        public string CUST_TEL { get; set; }
        public string CUST_TEL2 { get; set; }
        public string CUST_FAX { get; set; }
        public Nullable<decimal> BUSINESS_AMT { get; set; }
        public string CLOSE_YN { get; set; }
        public string AC_TYPE { get; set; }
        public Nullable<double> AC_RATE { get; set; }
        public Nullable<double> CASH_DISC_RATE { get; set; }
        public string INTERNATIONAL_TYPE { get; set; }
        public string SOURCE_TYPE { get; set; }
        public string OP_CORP { get; set; }
        public Nullable<int> PAY_DAYS { get; set; }
        public string GROUP_CORP { get; set; }
        public string BU_TEAM { get; set; }
        public string BU_GROUP { get; set; }
        public string DAN_CLIENT { get; set; }
        public string ADVERTISER { get; set; }
        public string GROUP_CLIENT { get; set; }
        public string CLIENT_TAGS { get; set; }
        public string VOUCHER_REMARK { get; set; }
        public string ENTRY_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
    }
}
