//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANMIS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactoryItems()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int SequenceNo { get; set; }
        public System.Guid ID { get; set; }
        public string ItemName { get; set; }
        public string ItemSpecification { get; set; }
        public string ItemClass { get; set; }
        public string ItemUnit { get; set; }
        public double ItemPrice { get; set; }
        public int ItemQty { get; set; }
        public string Factory { get; set; }
        public bool IsForStationery { get; set; }
        public bool IsForColleague { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool IsInventoryMgmt { get; set; }
        public bool IsAttached { get; set; }
        public int ItemRequisitionQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
    }
}
