#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/11/2021 11:08:16
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DANMIS_NEW.Models
{
    public interface IBadProjectDataRepository : IRepository<BadProjectData>
    {
    }
}
#pragma warning restore 1591
