#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/05/2021 16:39:39
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DANMIS_NEW.Models
{
    public interface IFloorManagerRepository : IRepository<FloorManager>
    {
    }
}
#pragma warning restore 1591
