//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANMIS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonChargeable
    {
        public int SequenceNo { get; set; }
        public System.Guid ID { get; set; }
        public string WORK_CARD_NO { get; set; }
        public string ProjectName { get; set; }
        public string StartDate { get; set; }
        public string CompleteDate { get; set; }
        public string Description { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectOwnerID { get; set; }
        public string OwnerEmail { get; set; }
        public string PortfolioName { get; set; }
        public string PortfolioOwnerID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramOwnerID { get; set; }
        public string CurrencyINR { get; set; }
        public string Budget { get; set; }
        public string Benefit { get; set; }
        public string ClientName { get; set; }
        public string LineofBusiness { get; set; }
        public string Region { get; set; }
        public string BrandName { get; set; }
        public string Market { get; set; }
        public string Office { get; set; }
        public string Chargeable { get; set; }
        public string Commission { get; set; }
        public string GroupName { get; set; }
        public string AccProjID { get; set; }
        public string LegalEntity { get; set; }
        public string FinSourSys { get; set; }
        public string CRMURNID { get; set; }
        public string CRMSourSys { get; set; }
        public string OtherSource { get; set; }
        public string AdditionalProjectID { get; set; }
        public string RecordStatus { get; set; }
        public System.DateTime ImportDate { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int ImportUniqNo { get; set; }
        public string ImportLocName { get; set; }
        public string ImportEngName { get; set; }
        public int UploadUniqNo { get; set; }
        public string UploadLocName { get; set; }
        public string UploadEngName { get; set; }
        public System.DateTime CompareDate { get; set; }
        public int CompareUniqNo { get; set; }
        public string CompareLocName { get; set; }
        public string CompareEngName { get; set; }
        public string ImportType { get; set; }
        public string ProjectID { get; set; }
        public string MediaType { get; set; }
        public string ProjectType { get; set; }
    }
}
