//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANMIS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSF0301
    {
        public System.Guid UNIQ_KEY { get; set; }
        public string CORP_NO { get; set; }
        public string EMP_NO { get; set; }
        public string CARD_TIMES { get; set; }
        public string EMP_ID { get; set; }
        public string INCOME_TAX_MARK { get; set; }
        public string ERROR_MARK_Y { get; set; }
        public string DEDUCT_TYPE { get; set; }
        public string EMP_NAME_CHI { get; set; }
        public string EMP_NAME_ENG { get; set; }
        public string EMP_NAME_ABBR { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string SEX { get; set; }
        public string BLOOD_TYPE { get; set; }
        public Nullable<decimal> BODY_TALL { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string ZIP_PERM_ADDR { get; set; }
        public string PERM_ADDR { get; set; }
        public string PERM_TEL { get; set; }
        public string ZIP_CONT_ADDR { get; set; }
        public string CONT_ADDR { get; set; }
        public string CONT_TEL { get; set; }
        public string TEL_NO { get; set; }
        public string EMAIL { get; set; }
        public string NATIONALITY_YN { get; set; }
        public string NATIONALITY { get; set; }
        public string PASSPORT { get; set; }
        public string MILITARY_SERVICE { get; set; }
        public Nullable<System.DateTime> LEAVE_ARMY_DATE { get; set; }
        public string PARTY_MEMBERSHIP { get; set; }
        public string RELIGION { get; set; }
        public string BODY_STATUS_REMK { get; set; }
        public string MARRIAGE_STATUS { get; set; }
        public string SPOUSE_NAME { get; set; }
        public Nullable<int> BRING_MANS { get; set; }
        public string EMP_TYPE { get; set; }
        public string SALARY_TYPE { get; set; }
        public string TAKE_OFFICE_MODE { get; set; }
        public Nullable<System.DateTime> TAKE_OFFICE_DATE { get; set; }
        public Nullable<System.DateTime> TRIAL_STOP_DATE { get; set; }
        public Nullable<System.DateTime> TEAM_TAKE_OFFICE_DATE { get; set; }
        public Nullable<System.DateTime> TAKE_WORK_DATE { get; set; }
        public string KIND { get; set; }
        public Nullable<System.DateTime> LEAVE_JOB_DATE { get; set; }
        public Nullable<System.DateTime> STOP_SAL_RETAIN_OFFICE_END { get; set; }
        public string SUB_TEL { get; set; }
        public string CORP_EMAIL { get; set; }
        public string LEAVE_JOB_REASON { get; set; }
        public string DEPT_NO_NOW { get; set; }
        public Nullable<System.DateTime> DEPT_EFFE_DATE_NOW { get; set; }
        public string PRO_NOW { get; set; }
        public Nullable<System.DateTime> PROFESS_TITLE_EFFE_DATE_NOW { get; set; }
        public string JOB_STEP_CODE_NOW { get; set; }
        public string JOB_GRADE_CODE_NOW { get; set; }
        public Nullable<System.DateTime> JOB_STEP_GRADE_EFFE_NOW { get; set; }
        public Nullable<int> TAKE_OFFICE_WORK_MM { get; set; }
        public Nullable<int> TAKE_OFFICE_WORK_YY { get; set; }
        public string BRUSH_CARD_YN { get; set; }
        public string LABOR_UNION_YN { get; set; }
        public string WOMAN_CLUB { get; set; }
        public string CHIEF_EXAM { get; set; }
        public byte[] HEAD_IMG_PATH { get; set; }
        public byte[] AUTOBIO_PATH { get; set; }
        public byte[] RECRUITE_PATH { get; set; }
        public byte[] EMP_SIGN_CHI { get; set; }
        public byte[] EMP_SIGN_ENG { get; set; }
        public string LIVE_PATH { get; set; }
        public string BANK_NO { get; set; }
        public string ACCT_NO { get; set; }
        public string RELA_NAME { get; set; }
        public string BANK_NO_2 { get; set; }
        public string ACCT_NO_2 { get; set; }
        public string RELA_NAME_2 { get; set; }
        public string LIAISON_NAME { get; set; }
        public string LIAISON_TEL { get; set; }
        public string LIAISON_ADDR { get; set; }
        public string LIAISON_RELA { get; set; }
        public string LIAISON_EMAIL { get; set; }
        public string GUAR_NAME1 { get; set; }
        public string GUAR_ID1 { get; set; }
        public string GUAR_RELA1 { get; set; }
        public string GUAR_CAREER1 { get; set; }
        public string GUAR_TEL1 { get; set; }
        public string GUAR_ADDR1 { get; set; }
        public string GUAR_EMAIL1 { get; set; }
        public string GUAR_NAME2 { get; set; }
        public string GUAR_ID2 { get; set; }
        public string GUAR_RELA2 { get; set; }
        public string GUAR_CAREER2 { get; set; }
        public string GUAR_TEL2 { get; set; }
        public string GUAR_ADDR2 { get; set; }
        public string GUAR_EMAIL2 { get; set; }
        public string VOUCHER_REMARK { get; set; }
        public string NOT_EMP_CAL { get; set; }
        public string STAY_LICENSE_NO { get; set; }
        public Nullable<System.DateTime> SLICENSE_DATE_ST { get; set; }
        public Nullable<System.DateTime> SLICENSE_DATE_END { get; set; }
        public string WLICENSE_NO { get; set; }
        public Nullable<System.DateTime> WLICENSE_DATE_ST { get; set; }
        public Nullable<System.DateTime> WLICENSE_DATE_END { get; set; }
        public string AGENCY_CORP { get; set; }
        public string INSURE_YN { get; set; }
        public Nullable<int> REST_YY { get; set; }
        public Nullable<int> REST_MM { get; set; }
        public string ENTRY_TYPE { get; set; }
        public string DEPT_BOSS_ALLOW_YN { get; set; }
        public Nullable<System.DateTime> DEPT_BOSS_ALLOW_DATE { get; set; }
        public string DEPT_BOSS_ALLOW_NAME { get; set; }
        public string ENTRY_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
        public string USC_FIELD_CHA_1 { get; set; }
        public string USC_FIELD_CHA_2 { get; set; }
        public string USC_FIELD_CHA_3 { get; set; }
        public string USC_FIELD_CHA_4 { get; set; }
        public Nullable<decimal> USC_FIELD_NUM_1 { get; set; }
        public Nullable<decimal> USC_FIELD_NUM_2 { get; set; }
        public Nullable<System.DateTime> USC_FIELD_DATE_1 { get; set; }
        public Nullable<System.DateTime> USC_FIELD_DATE_2 { get; set; }
        public string FIELD_CHA_1 { get; set; }
        public string FIELD_CHA_2 { get; set; }
        public string FIELD_CHA_3 { get; set; }
        public string FIELD_CHA_4 { get; set; }
        public string FIELD_CHA_5 { get; set; }
        public string SKIP { get; set; }
    }
}
