//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANMIS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WKF0001
    {
        public string CORP_NO { get; set; }
        public string WORK_CARD_NO { get; set; }
        public string CUST_NO { get; set; }
        public string PROD { get; set; }
        public string CREATE_EMP_NO { get; set; }
        public string MEDIA_KIND { get; set; }
        public string BUYER_TEAM { get; set; }
        public string WORK_CARD_MEDIA_TYPE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string GROUP_CARD_NO { get; set; }
        public string AMNET_TERM { get; set; }
        public string VOUCHER_REMARK { get; set; }
        public int DATA_SEQ { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string WORK_STEP { get; set; }
        public Nullable<decimal> BUDGET { get; set; }
        public string SECTION_NAME { get; set; }
        public Nullable<System.DateTime> DATE_ST { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public string RECEIVE_EMP_NO { get; set; }
        public string DEPUTY_EMP_NO { get; set; }
        public Nullable<System.DateTime> EXPECT_FINISH_DATE { get; set; }
        public Nullable<System.DateTime> REAL_FINISH_DATE { get; set; }
        public Nullable<System.DateTime> CUE_OK_DATE { get; set; }
        public string CANCEL_YN { get; set; }
        public string DETAIL_REMARK { get; set; }
        public string ENTRY_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
    }
}
