#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/12/2021 17:16:22
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class BrandItemsMgmtSearchModel : SearchModel
    {
        public Guid? BrandID { get; set; }

    }
}
#pragma warning restore 1591