#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/16/2021 12:14:15
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class CandidateSearchModel : SearchModel
    {
        public string CompCode { get; set; }
        public string WDID { get; set; }
        public string SearchName { get; set; }
    }
}
#pragma warning restore 1591