#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/28/2021 16:58:45
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class FactoryItemsSearchModel : SearchModel
    {        
        public Guid? ID { get; set; }
        [Display(Name = "Factory_Name", ResourceType = typeof(Resource))]
        public string Factory { get; set; }
        public SelectList _Factory { get; set; }
        [Display(Name = "ItemClass", ResourceType = typeof(Resource))]
        public string ItemClass { get; set; }
        public SelectList _ItemClass { get; set; }
    }
}
#pragma warning restore 1591