#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/11/2021 14:49:14
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class FloorManagerConfirmSearchModel : SearchModel
    {
        public Guid? ApplyWDID { get; set; }

        public Guid? ApplyItemID { get; set; }

    }
}
#pragma warning restore 1591