#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/10/2021 10:26:08
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class ItemsApplySearchModel : SearchModel
    {        
        // for 取得登入使用者的申請物品用
        public string ApplyWDID { get; set; }     

        public SelectList ItemList { get; set; }
        [Display(Name = "Item", ResourceType = typeof(Resource))]
        public string ItemID { get; set; }
        public SelectList ItemClassList { get; set; }
        public string ItemClass { get; set; }


    }
}
#pragma warning restore 1591