#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/16/2021 12:14:15
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel.ListResult;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DANMIS_NEW.ViewModel.SearchModel
{
    public class VotesSearchModel : SearchModel
    {
        public VotesSearchModel()
        {
            Candidates = new List<CandidateListResult>();
            ShowMsg = "您沒有投票權限唷!";
        }
        public List<CandidateListResult> Candidates { get; set; }

        public string WDID { get; set; }
        public bool CanVote { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string ShowMsg { get; set; }
        public SelectList BrandList { get; set; }
        public string Brand { get; set; }
    }
}
#pragma warning restore 1591