#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/28/2021 16:57:05
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NLog;
using ResourceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Utilities;
using Utilities.Attribute;
using Utilities.Utility;
using DANMIS_NEW.Interface;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Controllers
{
    public class FactoryItemsController : BaseController
    {
        public const string tableType = "FactoryItems";
        public const string uploadPath = "~/Content/Uploads/FactoryItems/";

        readonly ICommonManager _commonManager;
        readonly IFactoryItemsManager _factoryItemsManager;
        readonly IFactoryManager _factoryManager;
        readonly IItemClassManager _itemClassManager;
        readonly IItemsManager _itemsManager;

        public FactoryItemsController(
            ICommonManager commonManager,
            IFactoryItemsManager factoryItemsManager,
            IFactoryManager factoryManager,
            IItemClassManager itemClassManager,
            IItemsManager itemsManager)
        {
            _commonManager = commonManager;
            _factoryItemsManager = factoryItemsManager;
            _factoryManager = factoryManager;
            _itemClassManager = itemClassManager;
            _itemsManager = itemsManager;
            logger = LogManager.GetCurrentClassLogger();
        }

        /// <summary>
        /// 首頁
        /// </summary>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Index()
        {
            // 初始化查詢物件
            var searchModel = new FactoryItemsSearchModel();
            if (null != UnobtrusiveSession.Session["QueryModel"])
            {
                // 查詢條件存在 session 則取出
                var temp = UnobtrusiveSession.Session["QueryModel"] as FactoryItemsSearchModel;
                if (null != temp)
                {
                    searchModel = temp;
                }
            }

            searchModel._Factory = _factoryManager.GetSelectList();
            searchModel._ItemClass = _itemClassManager.GetSelectList();

            return View(searchModel);
        }

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        //[WebAuthorize(Code = "FactoryItemsIndex")]
        [HttpPost]
        public ActionResult Paging(FactoryItemsSearchModel searchModel)
        {
            // 查詢條件儲存於 session
            UnobtrusiveSession.Session["QueryModel"] = searchModel;
            // 查詢結果物件初始化
            var result = new Paging<FactoryItemsListResult> { total = 0, rows = null };
            // 查詢
            try
            {
                result = _factoryItemsManager.Paging(searchModel);
            }
            catch (Exception ex)
            {
                logger.Error(ex, string.Format(Resource.PagingError, Resource.FactoryItems));
            }

            return Json(result);
        }

        /// <summary>
        /// 檢視 FactoryItems 頁面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Details(Guid? id)
        {
            FactoryItemsViewModel viewModel = null;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                try
                {
                    // 讀取資料
                    viewModel = _factoryItemsManager.GetByID(id.Value);
                    if (null == viewModel)
                    {
                        // 查無資料
                        logger.Error(string.Format(Resource.NoData, Resource.FactoryItems, id.Value));
                        TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.NoData, Resource.FactoryItems, id.Value) }.ToString();
                    }
                }
                catch (Exception ex)
                {
                    // 查詢發生錯誤
                    logger.Error(ex, string.Format(Resource.GetDetailsDataError, Resource.FactoryItems, id.Value));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.GetDetailsDataError, Resource.FactoryItems, id.Value) }.ToString();
                }
            }
            else
            {
                // 參數錯誤
                logger.Error(string.Format(Resource.ParamError, Resource.Details));
                TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ParamError, Resource.Details) }.ToString();
            }
            // 查無資料轉回列表頁
            if (null == viewModel)
            {
                return RedirectToAction("Index");
            }
            // 初始化檢視頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 新增 FactoryItems 頁面
        /// </summary>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Create()
        {
            var viewModel = new FactoryItemsViewModel();
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 新增資料儲存
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Create(FactoryItemsViewModel viewModel)
        {
            // 驗證
            if (ModelState.IsValid)
            {
                try
                {
                    viewModel.ID = Guid.NewGuid();
                    viewModel.CreateUser = UserName;
                    viewModel.CreateTime = NowTime;
                    viewModel.UpdateUser = UserName;
                    viewModel.UpdateTime = NowTime;

                    //處理上傳多檔案
                    fileAttachedHandler(this, viewModel, viewModel.ID, uploadPath, tableType);

                    _factoryItemsManager.Create(viewModel);
                    UnobtrusiveSession.Session["QueryModel"] = null;
                    // 完成
                    TempData["ErrorMsg"] = new JsonMessage { Style = "success", Message = string.Format(Resource.ExecutionCompleted, Resource.Create, Resource.FactoryItems) }.ToString();
                    // 轉回列表頁
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // 儲存發生錯誤
                    logger.Error(ex, string.Format(Resource.ExecutionFailedWithID, Resource.Create, Resource.FactoryItems, viewModel.ID));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ExecutionFailedWithID, Resource.Create, Resource.FactoryItems, viewModel.ID) }.ToString();
                }
            }
            // 初始化新增頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 修改 FactoryItems 頁面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            FactoryItemsViewModel viewModel = null;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                try
                {
                    // 讀取資料
                    viewModel = _factoryItemsManager.GetByID(id.Value);
                    if (null == viewModel)
                    {
                        // 查無資料
                        logger.Error(string.Format(Resource.NoData, Resource.FactoryItems, id.Value));
                        TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.NoData, Resource.FactoryItems, id.Value) }.ToString();
                    }
                }
                catch (Exception ex)
                {
                    // 查詢發生錯誤
                    logger.Error(ex, string.Format(Resource.GetEditDataError, Resource.FactoryItems, id.Value));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.GetEditDataError, Resource.FactoryItems, id.Value) }.ToString();
                }
            }
            else
            {
                // 參數錯誤
                logger.Error(string.Format(Resource.ParamError, Resource.Edit));
                TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ParamError, Resource.Edit) }.ToString();
            }
            // 查無資料轉回列表頁
            if (null == viewModel)
            {
                return RedirectToAction("Index");
            }
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View("Create", viewModel);
        }

        /// <summary>
        /// 編輯資料儲存
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Edit(FactoryItemsViewModel viewModel)
        {
            // 驗證
            if (ModelState.IsValid)
            {
                try
                {
                    viewModel.UpdateUser = UserName;
                    viewModel.UpdateTime = NowTime;

                    //處理上傳多檔案
                    fileAttachedHandler(this, viewModel, viewModel.ID, uploadPath, tableType);

                    _factoryItemsManager.Update(viewModel);
                    // 完成
                    TempData["ErrorMsg"] = new JsonMessage { Style = "success", Message = string.Format(Resource.ExecutionCompleted, Resource.Edit, Resource.FactoryItems) }.ToString();
                    // 轉回列表頁
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // 儲存發生錯誤
                    logger.Error(ex, string.Format(Resource.ExecutionFailedWithID, Resource.Edit, Resource.FactoryItems, viewModel.ID));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ExecutionFailedWithID, Resource.Edit, Resource.FactoryItems, viewModel.ID) }.ToString();
                }
            }
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View("Create", viewModel);
        }

        /// <summary>
        /// 刪除機構資料
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Delete(List<Guid> id)
        {
            // 預設失敗
            var result = false;
            // id 有值進行刪除作業
            if (id != null && id.Any())
            {
                try
                {
                    // 進行刪除
                    _factoryItemsManager.Delete(id);
                    result = true;
                }
                catch (Exception ex)
                {
                    // 刪除失敗
                    logger.Error(ex, string.Format(Resource.ExecutionFailed, Resource.Delete, Resource.FactoryItems, id));
                }
            }

            return Json(result);
        }

        // 計算平均單價
        [HttpPost]
        public ActionResult GetNewQty(Guid id)
        {
            // 預設失敗
            var result = Json(new { result = false }, JsonRequestBehavior.AllowGet);

            // 取得所有此類別物品
            var items = _itemsManager.GetByFactoryID(id).Where(x => x.IsDeleted == false);

            if (items.Any())
            {
                try
                {
                    // 取得平均單價 & 回寫
                    double avarage = 0;
                    var qty = 0;
                    double totalPrice = 0;
                    foreach (var item in items)
                    {
                        totalPrice += item.ItemPrice * item.ItemQty;
                        qty += item.ItemQty;
                    }
                    avarage = totalPrice / qty;

                    // 更新FactoryItem
                    var factoryItem = _factoryItemsManager.GetByID(id);
                    factoryItem.ItemPrice = Math.Round(avarage, 2, MidpointRounding.AwayFromZero);
                    factoryItem.ItemQty = qty;
                    _factoryItemsManager.UpdateQty(factoryItem);

                    result = Json(new { result = true, price = factoryItem.ItemPrice, qty = qty }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    // 刪除失敗
                    logger.Error(ex, string.Format(Resource.ExecutionFailed, Resource.Delete, Resource.FactoryItems, id));
                }
            }

            return result;
        }

        // 計算平均單價
        [HttpPost]
        public ActionResult GetSelectList(string itemClass)
        {
            // 預設失敗
            var result = Json(new { result = false }, JsonRequestBehavior.AllowGet);

            // 取得所有此類別物品
            var items = _factoryItemsManager.GetSelectList(itemClass);

            result = Json(new { result = true, items = items }, JsonRequestBehavior.AllowGet);

            return result;
        }

        // 抓物品圖片
        [HttpPost]
        public ActionResult GetItemPic(string itemID)
        {
            // 預設失敗
            var result = Json(new { result = false }, JsonRequestBehavior.AllowGet);

            // 取得所有此類別物品
            if (!string.IsNullOrEmpty(itemID))
            {
                var itempics = _factoryItemsManager.GetByID(new Guid(itemID)).AttachedFiles;
                var picPath = itempics.FirstOrDefault().FilePath;
                result = Json(new { result = true, picPath = picPath }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult GetByID(Guid id)
        {
            // 預設失敗
            var result = Json(new { result = false }, JsonRequestBehavior.AllowGet);
            var factoryItem = _factoryItemsManager.GetByID(id);
                
            result = Json(new { result = true, factoryItem = factoryItem }, JsonRequestBehavior.AllowGet);

            return result;
        }

        /// <summary>
        /// 設定頁面所需要的下拉選單資料
        /// </summary>
        /// <param name="viewModel"></param>
        void setDropDownList(ref FactoryItemsViewModel viewModel)
        {
            viewModel.YesNoList = _commonManager.GetYesNoList();
            viewModel._ItemClass = _itemClassManager.GetSelectList();
            viewModel._Factory = _factoryManager.GetSelectList();
        }
    }
}
#pragma warning restore 1591