#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/12/2021 17:16:12
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class BrandItemsListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public Guid BrandItemsMgmtID { get; set; }
        public Guid FactoryItemID { get; set; }
        public string FactoryItemName { get; set; }
        public string ItemName { get; set; }
        public string ItemSpecification { get; set; }
        public string ItemClass { get; set; }
        public string ItemUnit { get; set; }
        public int ItemSafeQty { get; set; }
        public int ItemStockQty { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591