#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/12/2021 14:42:46
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class FactoryListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string FactoryName { get; set; }
        public string FactoryShortName { get; set; }
        public string IDNO { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string Address { get; set; }
        public string FactoryClass { get; set; }
        public bool IsShow { get; set; }
        public string Memo { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591