#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/11/2021 14:49:04
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class FloorManagerConfirmListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        [Display(Name = "ApplyWDID", ResourceType = typeof(Resource))]
        public string ApplyWDID { get; set; }
        [Display(Name = "ApplyName", ResourceType = typeof(Resource))]
        public string ApplyName { get; set; }
        [Display(Name = "AgnetWDID", ResourceType = typeof(Resource))]
        public string AgnetWDID { get; set; }
        [Display(Name = "AgentName", ResourceType = typeof(Resource))]
        public string AgentName { get; set; }
        [Display(Name = "ApplyBrand", ResourceType = typeof(Resource))]
        public string ApplyBrand { get; set; }
        [Display(Name = "ApplyItemID", ResourceType = typeof(Resource))]
        public Guid ApplyItemID { get; set; }
        [Display(Name = "ApplyItemName", ResourceType = typeof(Resource))]
        public string ApplyItemName { get; set; }
        [Display(Name = "ApplyQty", ResourceType = typeof(Resource))]
        public int ApplyQty { get; set; }
        public string Status { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591