#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/07/2021 11:47:31
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class HeadphoneListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string HeadphoneNumber { get; set; }
        public string Brand { get; set; }
        public string WDID { get; set; }
        public string User { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591