#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/03/2021 15:17:42
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class ItemsListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public Guid FactoryID { get; set; }
        public Guid FactoryItemID { get; set; }        
        public string ItemNO { get; set; }
        public string ItemName { get; set; }
        public string ItemUnit { get; set; }
        public double ItemPrice { get; set; }
        public int ItemQty { get; set; }
        public bool IsShow { get; set; }
        public bool IsDeleted { get; set; }
        public string FactoryName { get; set; }
        public string FactoryItemName { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591