#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/04/2021 15:25:23
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class ProjectDataListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string ProjectName { get; set; }
        public string StartDate { get; set; }
        public string Description { get; set; }
        public string CompleteDate { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectOwnerID { get; set; }
        public string OwnerEmail { get; set; }
        public string PortfolioName { get; set; }
        public string PortfolioOwnerID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramOwnerID { get; set; }
        public string CurrencyINR { get; set; }
        public string Budget { get; set; }
        public string Benefit { get; set; }
        public string ClientName { get; set; }
        public string LineofBusiness { get; set; }
        public string Region { get; set; }
        public string BrandName { get; set; }
        public string Market { get; set; }
        public string Office { get; set; }
        public string Chargeable { get; set; }
        public string ProjectType { get; set; }
        public string Commission { get; set; }
        public string GroupName { get; set; }
        public string AccProjID { get; set; }
        public string LegalEntity { get; set; }
        public string FinSourSys { get; set; }
        public string CRMURNID { get; set; }
        public string CRMSourSys { get; set; }
        public string OtherSource { get; set; }
        public string AdditionalProjectID { get; set; }
        public string RecordStatus { get; set; }
        public DateTime ImportDate { get; set; }
        public DateTime UploadDate { get; set; }
        public int ImportUniqNo { get; set; }
        public string ImportLocName { get; set; }
        public string ImportEngName { get; set; }
        public int UploadUniqNo { get; set; }
        public string UploadLocName { get; set; }
        public string UploadEngName { get; set; }
        public DateTime CompareDate { get; set; }
        public int CompareUniqNo { get; set; }
        public string CompareLocName { get; set; }
        public string CompareEngName { get; set; }
        

        public string CUST_NO_NAME { get; set; }
        public string PROD_NAME { get; set; }
        public string CREATE_EMP_NO_NAME { get; set; }
        public string MEDIA_KIND_NAME { get; set; }
        public string BUYER_TEAM_NAME { get; set; }
        public string WORK_CARD_MEDIA_TYPE_NAME { get; set; }
        public string WORK_STEP_NAME { get; set; }
        public string RECEIVE_EMP_NO_NAME { get; set; }
        public string DEPUTY_EMP_NO_NAME { get; set; }
        public string BU_CODE { get; set; }
        public string BU_CODE_NAME { get; set; }
        public string AMNET_TERM_NAME { get; set; }

        public string CUST_ABBR { get; set; }
        public string CORP_NO { get; set; }
        public string CUST_NO { get; set; }
        public string MEDIA_KIND { get; set; }
        public string PROD { get; set; }

        public string CompName { get; set; }
        public string WORK_CARD_NO { get; set; }
        public string ImportType { get; set; }
        public string ProjectID { get; set; }
        public string MediaType { get; set; }        

    }
}
#pragma warning restore 1591