#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 12:57:55
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class UserListResult
    {
        private string _photoPath;

        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public bool IsEnable { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
        public DateTime LoginTime { get; set; }
        public string PhotoPath
        {
            get
            {
                return string.Format("<img src=\"{0}\" width=\"24\" onerror=\"this.src='/Content/images/none_photo.jpg';\"/>", _photoPath);
            }
            set
            {
                _photoPath = value;
            }
        }
        public string DefaultIndex { get; set; }
        public string Department { get; set; }
        /// <summary>
        /// EmpUniqNo
        /// </summary>        
        [Display(Name = "WDID", ResourceType = typeof(Resource))]
        public string WDID { get; set; }

        /// <summary>
        /// EmpEngName
        /// </summary>        
        [Display(Name = "EmpEngName", ResourceType = typeof(Resource))]
        public string EmpEngName { get; set; }

        /// <summary>
        /// RegionCode
        /// </summary>        
        [Display(Name = "RegionCode", ResourceType = typeof(Resource))]
        public string RegionCode { get; set; }

        /// <summary>
        /// CompCode
        /// </summary>        
        [Display(Name = "CompCode", ResourceType = typeof(Resource))]
        public string CompCode { get; set; }

        /// <summary>
        /// OfficeCode
        /// </summary>        
        [Display(Name = "OfficeCode", ResourceType = typeof(Resource))]
        public string OfficeCode { get; set; }

        /// <summary>
        /// DeptCode
        /// </summary>        
        [Display(Name = "DeptCode", ResourceType = typeof(Resource))]
        public string DeptCode { get; set; }

        /// <summary>
        /// EmpNo
        /// </summary>        
        [Display(Name = "EmpNo", ResourceType = typeof(Resource))]
        public string EmpNo { get; set; }

        /// <summary>
        /// EmpEngOfficialName
        /// </summary>        
        [Display(Name = "EmpEngOfficialName", ResourceType = typeof(Resource))]
        public string EmpEngOfficialName { get; set; }

        /// <summary>
        /// EmpLocName
        /// </summary>        
        [Display(Name = "EmpLocName", ResourceType = typeof(Resource))]
        public string EmpLocName { get; set; }

        /// <summary>
        /// EmpGender
        /// </summary>        
        [Display(Name = "EmpGender", ResourceType = typeof(Resource))]
        public string EmpGender { get; set; }

        /// <summary>
        /// JobTitleCode
        /// </summary>        
        [Display(Name = "JobTitleCode", ResourceType = typeof(Resource))]
        public string JobTitleCode { get; set; }

        /// <summary>
        /// EmpStartDate
        /// </summary>        
        [Display(Name = "EmpStartDate", ResourceType = typeof(Resource))]
        public DateTime EmpStartDate { get; set; }

        /// <summary>
        /// EmpQuitDate
        /// </summary>        
        [Display(Name = "EmpQuitDate", ResourceType = typeof(Resource))]
        public DateTime EmpQuitDate { get; set; }


        /// <summary>
        /// EmpStatusCode
        /// </summary>        
        [Display(Name = "EmpStatusCode", ResourceType = typeof(Resource))]
        public string EmpStatusCode { get; set; }


        /// <summary>
        /// JobStatusCode
        /// </summary>        
        [Display(Name = "JobStatusCode", ResourceType = typeof(Resource))]
        public string JobStatusCode { get; set; }

        /// <summary>
        /// EmpCompEmail
        /// </summary>        
        [Display(Name = "EmpCompEmail", ResourceType = typeof(Resource))]
        public string EmpCompEmail { get; set; }

        /// <summary>
        /// EmpADLoginID
        /// </summary>        
        [Display(Name = "EmpADLoginID", ResourceType = typeof(Resource))]
        public string EmpADLoginID { get; set; }

        /// <summary>
        /// EmpComputerID
        /// </summary>        
        [Display(Name = "EmpComputerID", ResourceType = typeof(Resource))]
        public string EmpComputerID { get; set; }

        /// <summary>
        /// EmpPrivateEMail
        /// </summary>        
        [Display(Name = "EmpPrivateEMail", ResourceType = typeof(Resource))]
        public string EmpPrivateEMail { get; set; }

        /// <summary>
        /// EmpHomePhone
        /// </summary>        
        [Display(Name = "EmpHomePhone", ResourceType = typeof(Resource))]
        public string EmpHomePhone { get; set; }

        /// <summary>
        /// EmpMobilePhone
        /// </summary>        
        [Display(Name = "EmpMobilePhone", ResourceType = typeof(Resource))]
        public string EmpMobilePhone { get; set; }

        /// <summary>
        /// BossEmpUniqNo
        /// </summary>        
        [Display(Name = "BossEmpUniqNo", ResourceType = typeof(Resource))]
        public string BossEmpUniqNo { get; set; }

        /// <summary>
        /// EmpAcctStatus
        /// </summary>        
        [Display(Name = "EmpAcctStatus", ResourceType = typeof(Resource))]
        public string EmpAcctStatus { get; set; }

        /// <summary>
        /// WritingLanguage
        /// </summary>        
        [Display(Name = "WritingLanguage", ResourceType = typeof(Resource))]
        public string WritingLanguage { get; set; }

        /// <summary>
        /// SysLanguage
        /// </summary>        
        [Display(Name = "SysLanguage", ResourceType = typeof(Resource))]
        public string SysLanguage { get; set; }

        /// <summary>
        /// EmpBankAccount
        /// </summary>        
        [Display(Name = "EmpBankAccount", ResourceType = typeof(Resource))]
        public string EmpBankAccount { get; set; }

        /// <summary>
        /// EmpPhoto
        /// </summary>        
        [Display(Name = "EmpPhoto", ResourceType = typeof(Resource))]
        public string EmpPhoto { get; set; }

        /// <summary>
        /// CheckAttendance
        /// </summary>        
        [Display(Name = "CheckAttendance", ResourceType = typeof(Resource))]
        public string CheckAttendance { get; set; }

        /// <summary>
        /// ExtDisplayFlag
        /// </summary>        
        [Display(Name = "UserExtIsShow", ResourceType = typeof(Resource))]
        public bool UserExtIsShow { get; set; }

        /// <summary>
        /// NextBossEmpUniqNo
        /// </summary>        
        [Display(Name = "NextBossEmpUniqNo", ResourceType = typeof(Resource))]
        public string NextBossEmpUniqNo { get; set; }

        /// <summary>
        /// EmpExtNo
        /// </summary>        
        [Display(Name = "EmpExtNo", ResourceType = typeof(Resource))]
        public string EmpExtNo { get; set; }

        /// <summary>
        /// TaxiAccount
        /// </summary>        
        [Display(Name = "TaxiAccount", ResourceType = typeof(Resource))]
        public string TaxiAccount { get; set; }

        /// <summary>
        /// BrandCode
        /// </summary>        
        [Display(Name = "BrandCode", ResourceType = typeof(Resource))]
        public string BrandCode { get; set; }

        /// <summary>
        /// EmpType
        /// </summary>        
        [Display(Name = "EmpType", ResourceType = typeof(Resource))]
        public string EmpType { get; set; }

        /// <summary>
        /// LastWorkDate
        /// </summary>        
        [Display(Name = "LastWorkDate", ResourceType = typeof(Resource))]
        public DateTime LastWorkDate { get; set; }

        /// <summary>
        /// CardNo
        /// </summary>        
        [Display(Name = "CardNo", ResourceType = typeof(Resource))]
        public string CardNo { get; set; }

        /// <summary>
        /// FloorNo
        /// </summary>        
        [Display(Name = "FloorNo", ResourceType = typeof(Resource))]
        public string FloorNo { get; set; }

        /// <summary>
        /// SeatNo
        /// </summary>        
        [Display(Name = "SeatNo", ResourceType = typeof(Resource))]
        public string SeatNo { get; set; }

        /// <summary>
        /// MotoNo
        /// </summary>        
        [Display(Name = "MotoNo", ResourceType = typeof(Resource))]
        public string MotoNo { get; set; }

        /// <summary>
        /// MotocycleID
        /// </summary>        
        [Display(Name = "MotocycleID", ResourceType = typeof(Resource))]
        public string MotocycleID { get; set; }

        /// <summary>
        /// ETag
        /// </summary>        
        [Display(Name = "ETag", ResourceType = typeof(Resource))]
        public string ETag { get; set; }

        /// <summary>
        /// MotoStartDate
        /// </summary>        
        [Display(Name = "MotoStartDate", ResourceType = typeof(Resource))]
        public DateTime MotoStartDate { get; set; }

        /// <summary>
        /// FaxNo
        /// </summary>        
        [Display(Name = "FaxNo", ResourceType = typeof(Resource))]
        public string FaxNo { get; set; }

        /// <summary>
        /// LeaseLine
        /// </summary>        
        [Display(Name = "LeaseLine", ResourceType = typeof(Resource))]
        public string LeaseLine { get; set; }

        /// <summary>
        /// AssestNo
        /// </summary>        
        [Display(Name = "AssestNo", ResourceType = typeof(Resource))]
        public string AssestNo { get; set; }

        /// <summary>
        /// ThirdCode
        /// </summary>        
        [Display(Name = "ThirdCode", ResourceType = typeof(Resource))]
        public string ThirdCode { get; set; }
    }
}
#pragma warning restore 1591