#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/16/2021 12:14:06
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class VotesListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public string Company { get; set; }
        public string VoteTo { get; set; }
        public DateTime VoteDate { get; set; }
    }
}
#pragma warning restore 1591