#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/04/2021 15:25:23
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DANMIS_NEW.ViewModel.ListResult
{
    public class WorkfrontImportListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public string GroupName { get; set; }
        public string IsChargeable { get; set; }
        public string ProjectType { get; set; }
        public string ProjectID { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591