#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/11/2021 11:08:00
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DANMIS_NEW.Models;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Interface
{
    public interface IBadProjectDataManager : IManager
    {
        /// <summary>
        /// 建立 BadProjectData
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(BadProjectDataViewModel entity);

        /// <summary>
        /// 根據 id 刪除 BadProjectData
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 BadProjectData
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        BadProjectDataViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<BadProjectDataListResult> Paging(BadProjectDataSearchModel searchModel);

        /// <summary>
        /// 更新 BadProjectData
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(BadProjectDataViewModel entity);

        List<BadProjectDataViewModel> GetAll();
    }
}
#pragma warning restore 1591