#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/28/2021 11:02:15
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Interface
{
    public interface IDIDManager : IManager
    {
        /// <summary>
        /// 建立 DID
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(DIDViewModel entity);

        /// <summary>
        /// 根據 id 刪除 DID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 DID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        DIDViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<DIDListResult> Paging(DIDSearchModel searchModel);

        /// <summary>
        /// 更新 DID
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(DIDViewModel entity);

        SelectList GetSelectList(string brand, string did);
    }
}
#pragma warning restore 1591