#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/07/2021 11:46:23
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Interface
{
    public interface IHeadphoneManager : IManager
    {
        /// <summary>
        /// 建立 Headphone
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(HeadphoneViewModel entity);

        /// <summary>
        /// 根據 id 刪除 Headphone
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 Headphone
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        HeadphoneViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<HeadphoneListResult> Paging(HeadphoneSearchModel searchModel);

        /// <summary>
        /// 更新 Headphone
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(HeadphoneViewModel entity);

        SelectList GetSelectList(string brand, string headphone);
    }
}
#pragma warning restore 1591