#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/03/2021 15:16:30
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Interface
{
    public interface IItemsManager : IManager
    {
        /// <summary>
        /// 建立 Items
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(ItemsViewModel entity);

        /// <summary>
        /// 根據 id 刪除 Items
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 Items
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        ItemsViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<ItemsListResult> Paging(ItemsSearchModel searchModel);

        /// <summary>
        /// 更新 Items
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(ItemsViewModel entity);

        List<ItemsViewModel> GetByFactoryID(Guid id);
    }
}
#pragma warning restore 1591