#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/04/2021 15:24:21
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DANMIS_NEW.Models;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;

namespace DANMIS_NEW.Interface
{
    public interface IWorkfrontReportManager : IManager
    {
        /// <summary>
        /// 建立 WorkfrontReport
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(WorkfrontReportViewModel entity);

        /// <summary>
        /// 根據 id 刪除 WorkfrontReport
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 WorkfrontReport
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        WorkfrontReportViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<WorkfrontReportListResult> Paging(WorkfrontReportSearchModel searchModel);

        /// <summary>
        /// 更新 WorkfrontReport
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(WorkfrontReportViewModel entity);

        List<WorkfrontReport> getReportExcelFile(string path, string user);

        //List<WorkfrontImport> getImportExcelFile(string path, string user);

        void insertResult(List<WorkfrontReport> reportData);
    }
}
#pragma warning restore 1591