#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/12/2021 17:15:28
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel;

namespace DANMIS_NEW.Models
{
    public partial class BrandItems
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static BrandItems Convert(BrandItemsViewModel source)
        {
            return source == null ? null : new BrandItems
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                BrandItemsMgmtID = source.BrandItemsMgmtID,
                FactoryItemID = source.FactoryItemID,
                ItemSafeQty = source.ItemSafeQty,
                ItemStockQty = source.ItemStockQty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static BrandItemsViewModel Convert(BrandItems source)
        {
            return source == null ? null : new BrandItemsViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                BrandItemsMgmtID = source.BrandItemsMgmtID,
                FactoryItemID = source.FactoryItemID,
                ItemSafeQty = source.ItemSafeQty,
                ItemStockQty = source.ItemStockQty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator BrandItems(BrandItemsViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator BrandItemsViewModel(BrandItems source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591