#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/12/2021 15:45:49
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel;

namespace DANMIS_NEW.Models
{
    public partial class ContactPerson
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static ContactPerson Convert(ContactPersonViewModel source)
        {
            return source == null ? null : new ContactPerson
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                FactoryID = source.FactoryID,
                Name = source.Name ?? string.Empty,
                TEL = source.TEL ?? string.Empty,
                FAX = source.FAX ?? string.Empty,
                CellPhone = source.CellPhone ?? string.Empty,
                Email = source.Email ?? string.Empty,
                Memo = source.Memo ?? string.Empty,
                IsShow = source.IsShow ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static ContactPersonViewModel Convert(ContactPerson source)
        {
            return source == null ? null : new ContactPersonViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                FactoryID = source.FactoryID,
                Name = source.Name ?? string.Empty,
                TEL = source.TEL ?? string.Empty,
                FAX = source.FAX ?? string.Empty,
                CellPhone = source.CellPhone ?? string.Empty,
                Email = source.Email ?? string.Empty,
                Memo = source.Memo ?? string.Empty,
                IsShow = source.IsShow ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator ContactPerson(ContactPersonViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator ContactPersonViewModel(ContactPerson source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591