#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/12/2021 14:42:03
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel;

namespace DANMIS_NEW.Models
{
    public partial class Factory
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Factory Convert(FactoryViewModel source)
        {
            return source == null ? null : new Factory
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                FactoryName = source.FactoryName ?? string.Empty,
                FactoryShortName = source.FactoryShortName ?? string.Empty,
                IDNO = source.IDNO ?? string.Empty,
                TEL = source.TEL ?? string.Empty,
                FAX = source.FAX ?? string.Empty,
                Address = source.Address ?? string.Empty,
                FactoryClass = source.FactoryClass ?? string.Empty,
                IsShow = source.IsShow,
                Memo = source.Memo ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FactoryViewModel Convert(Factory source)
        {
            return source == null ? null : new FactoryViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                FactoryName = source.FactoryName ?? string.Empty,
                FactoryShortName = source.FactoryShortName ?? string.Empty,
                IDNO = source.IDNO ?? string.Empty,
                TEL = source.TEL ?? string.Empty,
                FAX = source.FAX ?? string.Empty,
                Address = source.Address ?? string.Empty,
                FactoryClass = source.FactoryClass ?? string.Empty,
                IsShow = source.IsShow,
                Memo = source.Memo ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Factory(FactoryViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FactoryViewModel(Factory source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591