#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 03/04/2021 15:24:54
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel;

namespace DANMIS_NEW.Models
{
    public partial class ProjectData
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static ProjectData Convert(ProjectDataViewModel source)
        {
            return source == null ? null : new ProjectData
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                WORK_CARD_NO = source.WORK_CARD_NO ?? string.Empty,
                ProjectName = source.ProjectName ?? string.Empty,
                StartDate = source.StartDate ?? string.Empty,
                CompleteDate = source.CompleteDate ?? string.Empty,
                Description = source.Description ?? string.Empty,
                ProjectStatus = source.ProjectStatus ?? string.Empty,
                ProjectOwnerID = source.ProjectOwnerID ?? string.Empty,
                OwnerEmail = source.OwnerEmail ?? string.Empty,
                PortfolioName = source.PortfolioName ?? string.Empty,
                PortfolioOwnerID = source.PortfolioOwnerID ?? string.Empty,
                ProgramName = source.ProgramName ?? string.Empty,
                ProgramOwnerID = source.ProgramOwnerID ?? string.Empty,
                CurrencyINR = source.CurrencyINR ?? string.Empty,
                Budget = source.Budget ?? string.Empty,
                Benefit = source.Benefit ?? string.Empty,
                ClientName = source.ClientName ?? string.Empty,
                LineofBusiness = source.LineofBusiness ?? string.Empty,
                Region = source.Region ?? string.Empty,
                BrandName = source.BrandName ?? string.Empty,
                Market = source.Market ?? string.Empty,
                Office = source.Office ?? string.Empty,
                Chargeable = source.Chargeable ?? string.Empty,
                Commission = source.Commission ?? string.Empty,
                GroupName = source.GroupName ?? string.Empty,
                AccProjID = source.AccProjID ?? string.Empty,
                LegalEntity = source.LegalEntity ?? string.Empty,
                FinSourSys = source.FinSourSys ?? string.Empty,
                CRMURNID = source.CRMURNID ?? string.Empty,
                CRMSourSys = source.CRMSourSys ?? string.Empty,
                OtherSource = source.OtherSource ?? string.Empty,
                AdditionalProjectID = source.AdditionalProjectID ?? string.Empty,
                RecordStatus = source.RecordStatus ?? string.Empty,
                ImportDate = source.ImportDate,
                UploadDate = source.UploadDate,
                ImportUniqNo = source.ImportUniqNo,
                ImportLocName = source.ImportLocName ?? string.Empty,
                ImportEngName = source.ImportEngName ?? string.Empty,
                UploadUniqNo = source.UploadUniqNo,
                UploadLocName = source.UploadLocName ?? string.Empty,
                UploadEngName = source.UploadEngName ?? string.Empty,
                CompareDate = source.CompareDate,
                CompareUniqNo = source.CompareUniqNo,
                CompareLocName = source.CompareLocName ?? string.Empty,
                CompareEngName = source.CompareEngName ?? string.Empty,
                ImportType = source.ImportType ?? string.Empty,
                ProjectID = source.ProjectID ?? string.Empty,
                MediaType = source.MediaType ?? string.Empty,
                ProjectType = source.ProjectType ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static ProjectDataViewModel Convert(ProjectData source)
        {
            return source == null ? null : new ProjectDataViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                WORK_CARD_NO = source.WORK_CARD_NO ?? string.Empty,
                ProjectName = source.ProjectName ?? string.Empty,
                StartDate = source.StartDate ?? string.Empty,
                CompleteDate = source.CompleteDate ?? string.Empty,
                Description = source.Description ?? string.Empty,
                ProjectStatus = source.ProjectStatus ?? string.Empty,
                ProjectOwnerID = source.ProjectOwnerID ?? string.Empty,
                OwnerEmail = source.OwnerEmail ?? string.Empty,
                PortfolioName = source.PortfolioName ?? string.Empty,
                PortfolioOwnerID = source.PortfolioOwnerID ?? string.Empty,
                ProgramName = source.ProgramName ?? string.Empty,
                ProgramOwnerID = source.ProgramOwnerID ?? string.Empty,
                CurrencyINR = source.CurrencyINR ?? string.Empty,
                Budget = source.Budget ?? string.Empty,
                Benefit = source.Benefit ?? string.Empty,
                ClientName = source.ClientName ?? string.Empty,
                LineofBusiness = source.LineofBusiness ?? string.Empty,
                Region = source.Region ?? string.Empty,
                BrandName = source.BrandName ?? string.Empty,
                Market = source.Market ?? string.Empty,
                Office = source.Office ?? string.Empty,
                Chargeable = source.Chargeable ?? string.Empty,
                Commission = source.Commission ?? string.Empty,
                GroupName = source.GroupName ?? string.Empty,
                AccProjID = source.AccProjID ?? string.Empty,
                LegalEntity = source.LegalEntity ?? string.Empty,
                FinSourSys = source.FinSourSys ?? string.Empty,
                CRMURNID = source.CRMURNID ?? string.Empty,
                CRMSourSys = source.CRMSourSys ?? string.Empty,
                OtherSource = source.OtherSource ?? string.Empty,
                AdditionalProjectID = source.AdditionalProjectID ?? string.Empty,
                RecordStatus = source.RecordStatus ?? string.Empty,
                ImportDate = source.ImportDate,
                UploadDate = source.UploadDate,
                ImportUniqNo = source.ImportUniqNo,
                ImportLocName = source.ImportLocName ?? string.Empty,
                ImportEngName = source.ImportEngName ?? string.Empty,
                UploadUniqNo = source.UploadUniqNo,
                UploadLocName = source.UploadLocName ?? string.Empty,
                UploadEngName = source.UploadEngName ?? string.Empty,
                CompareDate = source.CompareDate,
                CompareUniqNo = source.CompareUniqNo,
                CompareLocName = source.CompareLocName ?? string.Empty,
                CompareEngName = source.CompareEngName ?? string.Empty,
                ImportType = source.ImportType ?? string.Empty,
                ProjectID = source.ProjectID ?? string.Empty,
                MediaType = source.MediaType ?? string.Empty,
                ProjectType = source.ProjectType ?? string.Empty,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator ProjectData(ProjectDataViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator ProjectDataViewModel(ProjectData source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591