#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 10/24/2017 11:43:17
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.Struct;

namespace DANMIS_NEW.Models
{
    public partial class User
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static User Convert(UserViewModel source)
        {
            return source == null ? null : new User
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Name = source.Name ?? string.Empty,
                Account = source.Account ?? string.Empty,
                Password = source.Password ?? string.Empty,
                Email = source.Email ?? string.Empty,
                ContactTel = source.ContactTel ?? string.Empty,
                WDID = source.WDID ?? string.Empty,
                StaffEvent = source.StaffEvent ?? string.Empty,
                EmpNo = source.EmpNo ?? string.Empty,
                PersonTitle = source.PersonTitle ?? string.Empty,
                LocalName = source.LocalName ?? string.Empty,
                FullEngName = source.FullEngName ?? string.Empty,
                LocEngName = source.LocEngName ?? string.Empty,
                EngFirstName = source.EngFirstName ?? string.Empty,
                EngMidName = source.EngMidName ?? string.Empty,
                EngLastName = source.EngLastName ?? string.Empty,
                WorkAdd1 = source.WorkAdd1 ?? string.Empty,
                WorkAdd2 = source.WorkAdd2 ?? string.Empty,
                WorkAdd3 = source.WorkAdd3 ?? string.Empty,
                WorkAdd4 = source.WorkAdd4 ?? string.Empty,
                WorkAddCountry = source.WorkAddCountry ?? string.Empty,
                HireDate = source.HireDate ?? string.Empty,
                HireReason = source.HireReason ?? string.Empty,
                ContStartDate = source.ContStartDate ?? string.Empty,
                ConEndDate = source.ConEndDate ?? string.Empty,
                CompName = source.CompName ?? string.Empty,
                CompEffDate = source.CompEffDate ?? string.Empty,
                CostCenterName = source.CostCenterName ?? string.Empty,
                CostCenterCode = source.CostCenterCode ?? string.Empty,
                CostCenterEffDate = source.CostCenterEffDate ?? string.Empty,
                Brand = source.Brand ?? string.Empty,
                BrandEffDate = source.BrandEffDate ?? string.Empty,
                BossLocEngName = source.BossLocEngName ?? string.Empty,
                BossWDID = source.BossWDID ?? string.Empty,
                EmpType = source.EmpType ?? string.Empty,
                GroupHireDate = source.GroupHireDate ?? string.Empty,
                EmpStartDate = source.EmpStartDate ?? string.Empty,
                DeptMgrName = source.DeptMgrName ?? string.Empty,
                DeptMgrWDID = source.DeptMgrWDID ?? string.Empty,
                DeptEffDate = source.DeptEffDate ?? string.Empty,
                PrimaryAdd1 = source.PrimaryAdd1 ?? string.Empty,
                PrimaryAddPostCost = source.PrimaryAddPostCost ?? string.Empty,
                PrimaryAddCity = source.PrimaryAddCity ?? string.Empty,
                PrimaryAddCountry = source.PrimaryAddCountry ?? string.Empty,
                PrimaryAddPhone = source.PrimaryAddPhone ?? string.Empty,
                PrimaryAddEmail = source.PrimaryAddEmail ?? string.Empty,
                DateOfBirth = source.DateOfBirth ?? string.Empty,
                Gender = source.Gender ?? string.Empty,
                Nationality = source.Nationality ?? string.Empty,
                MaritalStatus = source.MaritalStatus ?? string.Empty,
                CitiStatus = source.CitiStatus ?? string.Empty,
                MilitaryStatus = source.MilitaryStatus ?? string.Empty,
                PersonDataEffDate = source.PersonDataEffDate ?? string.Empty,
                Position = source.Position ?? string.Empty,
                PositionID = source.PositionID ?? string.Empty,
                TimeType = source.TimeType ?? string.Empty,
                PositionEffDate = source.PositionEffDate ?? string.Empty,
                JobID = source.JobID ?? string.Empty,
                JobProfile = source.JobProfile ?? string.Empty,
                JobProfileEffDate = source.JobProfileEffDate ?? string.Empty,
                JobTitle = source.JobTitle ?? string.Empty,
                BusinessTitle = source.BusinessTitle ?? string.Empty,
                BusinessEffDate = source.BusinessEffDate ?? string.Empty,
                ChangeJobReason = source.ChangeJobReason ?? string.Empty,
                ChangeJobDate = source.ChangeJobDate ?? string.Empty,
                TerminationDate = source.TerminationDate ?? string.Empty,
                TerminationReasonLoc = source.TerminationReasonLoc ?? string.Empty,
                TerminationReasonPri = source.TerminationReasonPri ?? string.Empty,
                LastWorkDate = source.LastWorkDate ?? string.Empty,
                NationalIDCountry = source.NationalIDCountry ?? string.Empty,
                NationalIDType = source.NationalIDType ?? string.Empty,
                NationalIDNo = source.NationalIDNo ?? string.Empty,
                RegionCode = source.RegionCode ?? string.Empty,
                CompCode = source.CompCode ?? string.Empty,
                DeptCode = source.DeptCode ?? string.Empty,
                UserComputerID = source.UserComputerID ?? string.Empty,
                UserHomePhone = source.UserHomePhone ?? string.Empty,
                UserMobilePhone = source.UserMobilePhone ?? string.Empty,
                UserExtNo = source.UserExtNo ?? string.Empty,
                UserExtIsShow = source.UserExtIsShow,
                TaxiAccount = source.TaxiAccount ?? string.Empty,
                BrandCode = source.BrandCode ?? string.Empty,
                CardNo = source.CardNo ?? string.Empty,
                FloorNo = source.FloorNo ?? string.Empty,
                SeatNo = source.SeatNo ?? string.Empty,
                MotoNo = source.MotoNo ?? string.Empty,
                MotocycleID = source.MotocycleID ?? string.Empty,
                ETag = source.ETag ?? string.Empty,
                MotoStartDate = source.MotoStartDate ?? string.Empty,
                FaxNo = source.FaxNo ?? string.Empty,
                LeaseLine = source.LeaseLine ?? string.Empty,
                AssestNo = source.AssestNo ?? string.Empty,
                ThirdCode = source.ThirdCode ?? string.Empty,
                BossEmpUniqNo = source.BossEmpUniqNo ?? string.Empty,
                NextBossEmpUniqNo = source.NextBossEmpUniqNo ?? string.Empty,
                IsEnable = source.IsEnable,
                PhotoPath = source.PhotoPath ?? string.Empty,
                IsToken = false,
                HashToken = source.HashToken ?? string.Empty,
                TokenData = string.Empty,
                FreeFields = null == source.FreeFields ? "{}" : source.FreeFields.ToString(),
                DefaultIndex = source.DefaultIndex,
                DepartmentID = source.DepartmentID,
                DepartmentIDs = JsonConvert.SerializeObject(source.DepartmentIDs),
                LoginTime = source.LoginTime,
                ChangePassTime = source.ChangePassTime,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
                TransDate = source.TransDate ?? string.Empty,
                TransTime = source.TransTime ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserViewModel Convert(User source)
        {
            var freeFields = null != source && !string.IsNullOrEmpty(source.FreeFields) ?
                new TemplateFields(source.FreeFields) :
                new TemplateFields();

            return source == null ? null : new UserViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Name = source.Name ?? string.Empty,
                Account = source.Account ?? string.Empty,
                Password = source.Password ?? string.Empty,
                Email = source.Email ?? string.Empty,
                ContactTel = source.ContactTel ?? string.Empty,
                WDID = source.WDID ?? string.Empty,
                StaffEvent = source.StaffEvent ?? string.Empty,
                EmpNo = source.EmpNo ?? string.Empty,
                PersonTitle = source.PersonTitle ?? string.Empty,
                LocalName = source.LocalName ?? string.Empty,
                FullEngName = source.FullEngName ?? string.Empty,
                LocEngName = source.LocEngName ?? string.Empty,
                EngFirstName = source.EngFirstName ?? string.Empty,
                EngMidName = source.EngMidName ?? string.Empty,
                EngLastName = source.EngLastName ?? string.Empty,
                WorkAdd1 = source.WorkAdd1 ?? string.Empty,
                WorkAdd2 = source.WorkAdd2 ?? string.Empty,
                WorkAdd3 = source.WorkAdd3 ?? string.Empty,
                WorkAdd4 = source.WorkAdd4 ?? string.Empty,
                WorkAddCountry = source.WorkAddCountry ?? string.Empty,
                HireDate = source.HireDate ?? string.Empty,
                HireReason = source.HireReason ?? string.Empty,
                ContStartDate = source.ContStartDate ?? string.Empty,
                ConEndDate = source.ConEndDate ?? string.Empty,
                CompName = source.CompName ?? string.Empty,
                CompEffDate = source.CompEffDate ?? string.Empty,
                CostCenterName = source.CostCenterName ?? string.Empty,
                CostCenterCode = source.CostCenterCode ?? string.Empty,
                CostCenterEffDate = source.CostCenterEffDate ?? string.Empty,
                Brand = source.Brand ?? string.Empty,
                BrandEffDate = source.BrandEffDate ?? string.Empty,
                BossLocEngName = source.BossLocEngName ?? string.Empty,
                BossWDID = source.BossWDID ?? string.Empty,
                EmpType = source.EmpType ?? string.Empty,
                GroupHireDate = source.GroupHireDate ?? string.Empty,
                EmpStartDate = source.EmpStartDate ?? string.Empty,
                DeptMgrName = source.DeptMgrName ?? string.Empty,
                DeptMgrWDID = source.DeptMgrWDID ?? string.Empty,
                DeptEffDate = source.DeptEffDate ?? string.Empty,
                PrimaryAdd1 = source.PrimaryAdd1 ?? string.Empty,
                PrimaryAddPostCost = source.PrimaryAddPostCost ?? string.Empty,
                PrimaryAddCity = source.PrimaryAddCity ?? string.Empty,
                PrimaryAddCountry = source.PrimaryAddCountry ?? string.Empty,
                PrimaryAddPhone = source.PrimaryAddPhone ?? string.Empty,
                PrimaryAddEmail = source.PrimaryAddEmail ?? string.Empty,
                DateOfBirth = source.DateOfBirth ?? string.Empty,
                Gender = source.Gender ?? string.Empty,
                Nationality = source.Nationality ?? string.Empty,
                MaritalStatus = source.MaritalStatus ?? string.Empty,
                CitiStatus = source.CitiStatus ?? string.Empty,
                MilitaryStatus = source.MilitaryStatus ?? string.Empty,
                PersonDataEffDate = source.PersonDataEffDate ?? string.Empty,
                Position = source.Position ?? string.Empty,
                PositionID = source.PositionID ?? string.Empty,
                TimeType = source.TimeType ?? string.Empty,
                PositionEffDate = source.PositionEffDate ?? string.Empty,
                JobID = source.JobID ?? string.Empty,
                JobProfile = source.JobProfile ?? string.Empty,
                JobProfileEffDate = source.JobProfileEffDate ?? string.Empty,
                JobTitle = source.JobTitle ?? string.Empty,
                BusinessTitle = source.BusinessTitle ?? string.Empty,
                BusinessEffDate = source.BusinessEffDate ?? string.Empty,
                ChangeJobReason = source.ChangeJobReason ?? string.Empty,
                ChangeJobDate = source.ChangeJobDate ?? string.Empty,
                TerminationDate = source.TerminationDate ?? string.Empty,
                TerminationReasonLoc = source.TerminationReasonLoc ?? string.Empty,
                TerminationReasonPri = source.TerminationReasonPri ?? string.Empty,
                LastWorkDate = source.LastWorkDate ?? string.Empty,
                NationalIDCountry = source.NationalIDCountry ?? string.Empty,
                NationalIDType = source.NationalIDType ?? string.Empty,
                NationalIDNo = source.NationalIDNo ?? string.Empty,
                RegionCode = source.RegionCode ?? string.Empty,
                CompCode = source.CompCode ?? string.Empty,
                DeptCode = source.DeptCode ?? string.Empty,
                UserComputerID = source.UserComputerID ?? string.Empty,
                UserHomePhone = source.UserHomePhone ?? string.Empty,
                UserMobilePhone = source.UserMobilePhone ?? string.Empty,
                UserExtNo = source.UserExtNo ?? string.Empty,
                UserExtIsShow = source.UserExtIsShow,
                TaxiAccount = source.TaxiAccount ?? string.Empty,
                BrandCode = source.BrandCode ?? string.Empty,
                CardNo = source.CardNo ?? string.Empty,
                FloorNo = source.FloorNo ?? string.Empty,
                SeatNo = source.SeatNo ?? string.Empty,
                MotoNo = source.MotoNo ?? string.Empty,
                MotocycleID = source.MotocycleID ?? string.Empty,
                ETag = source.ETag ?? string.Empty,
                MotoStartDate = source.MotoStartDate ?? string.Empty,
                FaxNo = source.FaxNo ?? string.Empty,
                LeaseLine = source.LeaseLine ?? string.Empty,
                AssestNo = source.AssestNo ?? string.Empty,
                ThirdCode = source.ThirdCode ?? string.Empty,
                BossEmpUniqNo = source.BossEmpUniqNo ?? string.Empty,
                NextBossEmpUniqNo = source.NextBossEmpUniqNo ?? string.Empty,
                IsEnable = source.IsEnable,
                PhotoPath = source.PhotoPath ?? string.Empty,
                HashToken = source.HashToken ?? string.Empty,
                FreeFields = freeFields,
                DefaultIndex = source.DefaultIndex,
                DepartmentID = source.DepartmentID,
                DepartmentIDs = JsonConvert.DeserializeObject<List<Guid>>(source.DepartmentIDs),
                RoleID = source.Role.Select(x => x.ID).ToList(),
                LoginTime = source.LoginTime,
                ChangePassTime = source.ChangePassTime,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
                TransDate = source.TransDate ?? string.Empty,
                TransTime = source.TransTime ?? string.Empty,

            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator User(UserViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserViewModel(User source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591