#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/16/2021 12:13:28
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DANMIS_NEW.ViewModel;

namespace DANMIS_NEW.Models
{
    public partial class Voter
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Voter Convert(VoterViewModel source)
        {
            return source == null ? null : new Voter
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                EmployeeID = source.EmployeeID ?? string.Empty,
                FirstName = source.FirstName ?? string.Empty,
                LastName = source.LastName ?? string.Empty,
                PreferredName = source.PreferredName ?? string.Empty,
                Company = source.Company ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static VoterViewModel Convert(Voter source)
        {
            return source == null ? null : new VoterViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                EmployeeID = source.EmployeeID ?? string.Empty,
                FirstName = source.FirstName ?? string.Empty,
                LastName = source.LastName ?? string.Empty,
                PreferredName = source.PreferredName ?? string.Empty,
                Company = source.Company ?? string.Empty,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Voter(VoterViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator VoterViewModel(Voter source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591