#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 05/07/2021 11:46:32
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Utilities.Extensions;
using DANMIS_NEW.Interface;
using DANMIS_NEW.Models;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;
using ResourceLibrary;
using System.Web.Mvc;

namespace DANMIS_NEW.Manager
{
    public class HeadphoneManager : IHeadphoneManager
    {
        readonly IHeadphoneRepository _headphoneRepository;
        readonly IUserRepository _userRepository;
        readonly ISystemOptionRepository _systemOptionRepository;

        public HeadphoneManager(IHeadphoneRepository headphoneRepository, IUserRepository userRepository, ISystemOptionRepository systemOptionRepository)
        {
            _headphoneRepository = headphoneRepository;
            _userRepository = userRepository;
            _systemOptionRepository = systemOptionRepository;
        }

        /// <summary>
        /// 建立 Headphone
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public void Create(HeadphoneViewModel entity)
        {
            var item = (Headphone)entity;

            using (var transaction = _headphoneRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    _headphoneRepository.Create(item);
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 刪除 Headphone
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public void Delete(List<Guid> id)
        {
            using (var transaction = _headphoneRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var itemSet = _headphoneRepository.Where(x => id.Contains(x.ID)).ToList();
                    if (itemSet.Any())
                    {
                        foreach (var item in itemSet)
                        {
                            _headphoneRepository.Delete(item);
                        }
                    }
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 取得 Headphone
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public HeadphoneViewModel GetByID(Guid id)
        {
            var item = _headphoneRepository.GetByID(id);
            var result = (HeadphoneViewModel)item;
            var user = _userRepository.GetAll().FirstOrDefault(x => x.WDID == result.WDID);
            if (user != null)
            {
                result.User.Name = string.Concat(user.EmpLocName, "(", user.EmpEngName, ")");
                result.User.Email = user.EmpCompEmail;
            }

            return result;
        }

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public Paging<HeadphoneListResult> Paging(HeadphoneSearchModel searchModel)
        {
            var headphoneStatus = _systemOptionRepository.GetAll().Where(x => x.Category == "HeadphoneStatus").ToList();
            // 預設集合
            var temp = _headphoneRepository.GetAll();

            // 將 DB 資料轉換為列表頁呈現資料
            var tempResult = from x in temp
                             select new HeadphoneListResult
                             {
                                 SequenceNo = x.SequenceNo,
                                 ID = x.ID,
                                 HeadphoneNumber = x.HeadphoneNumber,
                                 Brand = x.Brand,
                                 WDID = x.WDID,
                                 User = string.Empty,
                                 Email = string.Empty,
                                 Status = x.Status,
                                 UpdateUser = x.UpdateUser,
                                 UpdateTime = x.UpdateTime,
                             };

            // 如有篩選條件，進行篩選
            if (!string.IsNullOrWhiteSpace(searchModel.Search))
            {
                var search = searchModel.Search.ToLower();
                tempResult = tempResult.Where(x =>
                    x.HeadphoneNumber.Contains(search) ||
                    x.Brand.Contains(search) ||
                    x.WDID.Contains(search) ||                    
                    x.UpdateUser.Contains(search) ||
                    false);
            }

            if (!string.IsNullOrEmpty(searchModel.Brand))
                tempResult = tempResult.Where(x =>
                        x.Brand == searchModel.Brand ||
                        false);

            if (!string.IsNullOrEmpty(searchModel.Status))
                tempResult = tempResult.Where(x =>
                        x.Status == searchModel.Status ||
                        false);

            // 進行分頁處理
            var result = new Paging<HeadphoneListResult>();
            result.total = tempResult.Count();
            result.rows = tempResult
                .OrderBy(searchModel.Sort, searchModel.Order)
                .Skip(searchModel.Offset)
                .Take(searchModel.Limit)
                .ToList();

            var users = _userRepository.GetAll().Where(x => x.EmpQuitDate == null && x.WDID != null).ToList();

            foreach (var item in result.rows)
            {
                var user = users.FirstOrDefault(x => x.WDID == item.WDID);
                if (user != null)
                {
                    item.User = string.Concat(user.EmpLocName, "(", user.EmpEngName, ")");
                    item.Email = user.EmpCompEmail ?? string.Empty;                    
                }
                item.Status = headphoneStatus.FirstOrDefault(x => x.OptionKey == item.Status)?.OptionValue ?? "未配發";
            }

            return result;
        }

        /// <summary>
        /// 更新 Headphone
        /// </summary>
        /// <param name="entity"></param>
        public void Update(HeadphoneViewModel entity)
        {
            using (var transaction = _headphoneRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var source = _headphoneRepository.GetByID(entity.ID);
                    source.HeadphoneNumber = entity.HeadphoneNumber ?? string.Empty;
                    source.Brand = entity.Brand ?? string.Empty;
                    source.WDID = entity.WDID ?? string.Empty;
                    source.Status = entity.Status ?? string.Empty;
                    source.Memo = entity.Memo ?? string.Empty;
                    source.UpdateUser = entity.UpdateUser ?? string.Empty;
                    source.UpdateTime = entity.UpdateTime;

                    _headphoneRepository.Update(source);
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        public SelectList GetSelectList(string brand, string headphone)
        {
            // 預設集合
            var temp = _headphoneRepository.GetAll().Where(x => x.WDID == null || x.WDID == "" || x.HeadphoneNumber == headphone);

            // 將 DB 資料轉換為列表頁呈現資料
            var _tempResult = from x in temp
                              select new HeadphoneListResult
                              {
                                  SequenceNo = x.SequenceNo,
                                  ID = x.ID,
                                  HeadphoneNumber = x.HeadphoneNumber,
                                  Brand = x.Brand,
                                  WDID = x.WDID,
                                  User = string.Empty,
                                  Email = string.Empty,
                                  Status = x.Status,
                                  UpdateUser = x.UpdateUser,
                                  UpdateTime = x.UpdateTime,
                              };

            if (!string.IsNullOrEmpty(brand))
                _tempResult = _tempResult.Where(x =>
                    x.Brand == brand ||
                    false);

            // 進行分頁處理
            var tempResult = new Paging<HeadphoneListResult>();
            tempResult.total = _tempResult.Count();
            tempResult.rows = _tempResult.OrderBy("HeadphoneNumber", "asc").ToList();

            var list = new List<SelectListItem>();
            foreach (var item in tempResult.rows)
            {
                list.Add(new SelectListItem { Value = item.HeadphoneNumber, Text = item.HeadphoneNumber });
            }

            var result = new SelectList(list, "Value", "Text");

            return result;
        }
    }
}
#pragma warning restore 1591