#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 04/16/2021 12:13:09
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Utilities.Extensions;
using DANMIS_NEW.Interface;
using DANMIS_NEW.Models;
using DANMIS_NEW.ViewModel;
using DANMIS_NEW.ViewModel.ListResult;
using DANMIS_NEW.ViewModel.SearchModel;
using ResourceLibrary;

namespace DANMIS_NEW.Manager
{
    public class VoterManager : IVoterManager
    {
        readonly IVoterRepository _voterRepository;

        public VoterManager(IVoterRepository voterRepository)
        {
            _voterRepository = voterRepository;
        }

        /// <summary>
        /// 建立 Voter
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public void Create(VoterViewModel entity)
        {
            var item = (Voter)entity;

            using (var transaction = _voterRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    _voterRepository.Create(item);
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 刪除 Voter
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public void Delete(List<Guid> id)
        {
            using (var transaction = _voterRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var itemSet = _voterRepository.Where(x => id.Contains(x.ID)).ToList();
                    if (itemSet.Any())
                    {
                        foreach (var item in itemSet)
                        {
                            _voterRepository.Delete(item);
                        }
                    }
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 取得 Voter
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public VoterViewModel GetByID(Guid id)
        {
            var item = _voterRepository.GetByID(id);
            var result = (VoterViewModel)item;

            return result;
        }

        /// <summary>
        /// 根據 WDID 取得 Voter
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public VoterViewModel GetByWDID(string id)
        {
            var result = new VoterViewModel();
            var item = _voterRepository.GetAll().FirstOrDefault(x => x.EmployeeID == id);
            if(item != null)
                result = (VoterViewModel)item;

            return result;
        }


        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public Paging<VoterListResult> Paging(VoterSearchModel searchModel)
        {
            // 預設集合
            var temp = _voterRepository.GetAll();

            // 將 DB 資料轉換為列表頁呈現資料
            var tempResult = from x in temp
                             select new VoterListResult
                             {
                                 SequenceNo = x.SequenceNo,
                                 ID = x.ID,
                                 EmployeeID = x.EmployeeID,
                                 FirstName = x.FirstName,
                                 LastName = x.LastName,
                                 PreferredName = x.PreferredName,
                                 Company = x.Company,
                             };

            // 如有篩選條件，進行篩選
            if (!string.IsNullOrWhiteSpace(searchModel.Search))
            {
                var search = searchModel.Search.ToLower();
                tempResult = tempResult.Where(x =>
                    x.EmployeeID.Contains(search) ||
                    x.FirstName.Contains(search) ||
                    x.LastName.Contains(search) ||
                    x.PreferredName.Contains(search) ||
                    x.Company.Contains(search) ||
                    false);
            }

            // 進行分頁處理
            var result = new Paging<VoterListResult>();
            result.total = tempResult.Count();
            result.rows = tempResult
                .OrderBy(searchModel.Sort, searchModel.Order)
                .Skip(searchModel.Offset)
                .Take(searchModel.Limit)
                .ToList();

            return result;
        }

        /// <summary>
        /// 更新 Voter
        /// </summary>
        /// <param name="entity"></param>
        public void Update(VoterViewModel entity)
        {
            using (var transaction = _voterRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var source = _voterRepository.GetByID(entity.ID);
                    source.EmployeeID = entity.EmployeeID ?? string.Empty;
                    source.FirstName = entity.FirstName ?? string.Empty;
                    source.LastName = entity.LastName ?? string.Empty;
                    source.PreferredName = entity.PreferredName ?? string.Empty;
                    source.Company = entity.Company ?? string.Empty;

                    _voterRepository.Update(source);
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }
    }
}
#pragma warning restore 1591